### ISSUE TITLE
Fail to properly separate: some kind of argument issue.

### ISSUE THREAD

**Issue by interactiveaudiolab** [interactiveaudiolab/WUT#44]
2018-11-29 17:06:31] [    INFO] --- Max freq = 10206.73828125 Hz (general_audio.py:85)
127.0.0.1 - - [2018-11-29 17:06:32] "GET /socket.io/?EIO=3&transport=polling&t=MTXkH3r&sid=dc35f25d806f4835ac02e826e9648a56 HTTP/1.1" 200 223 14.658554
Matching file found at /tmp/.nussl/models/deep_clustering_vocals_44k_long.model, skipping download.
message handler error
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/engineio/server.py", line 423, in _trigger_event
    return self.handlers[event](*args)
  File "/anaconda3/lib/python3.7/site-packages/socketio/server.py", line 512, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/anaconda3/lib/python3.7/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/anaconda3/lib/python3.7/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/anaconda3/lib/python3.7/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/anaconda3/lib/python3.7/site-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/anaconda3/lib/python3.7/site-packages/flask_socketio/__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "/Users/bryan/Documents/GitHub/WUT/app/app/views.py", line 115, in initialize
    dc = audio_processing.DeepClusteringWUT(separation_sess.user_signal, separation_sess.user_original_file_folder, model_path)
  File "/Users/bryan/Documents/GitHub/WUT/app/app/audio_processing/deep_clustering.py", line 41, in __init__
    use_librosa_stft=True)
TypeError: __init__() takes 1 positional argument but 2 were given
[2018-11-29 17:06:32] [   ERROR] --- message handler error (server.py:425)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/engineio/server.py", line 423, in _trigger_event
    return self.handlers[event](*args)
  File "/anaconda3/lib/python3.7/site-packages/socketio/server.py", line 512, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/anaconda3/lib/python3.7/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/anaconda3/lib/python3.7/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/anaconda3/lib/python3.7/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/anaconda3/lib/python3.7/site-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/anaconda3/lib/python3.7/site-packages/flask_socketio/__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "/Users/bryan/Documents/GitHub/WUT/app/app/views.py", line 115, in initialize
    dc = audio_processing.DeepClusteringWUT(separation_sess.user_signal, separation_sess.user_original_file_folder, model_path)
  File "/Users/bryan/Documents/GitHub/WUT/app/app/audio_processing/deep_clustering.py", line 41, in __init__
    use_librosa_stft=True)
TypeError: __init__() takes 1 positional argument but 2 were given
127.0.0.1 - - [2018-11-29 17:06:32] "POST /socket.io/?EIO=3&transport=polling&t=MTXkKRM&sid=dc35f25d806f4835ac02e826e9648a56 HTTP/1.1" 200 195 1.238359
^CKeyboardInterrupt
2018-11-29T23:06:38Z
KeyboardInterrupt
2018-11-29T23:06:38Z

**Comment by nathanshelly** [comment]
This error is due to a bug in our implementation of a more helpful error message when `torch` not installed. Fix: `pip install torch`.

Going forward we've fixed the bug in our implementation so if you attempt to run `wut` w/o `torch` installed you should get a much more helpful error message which indicates that you need to install `torch`.
